openapi: 3.0.3
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /ingredients:
    get:
      summary: Retourne la liste de tous les ingrédients
      responses:
        '200':
          description: Liste des ingrédients retournée avec succès
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'

  /ingredients/{id}:
    get:
      summary: Retourne un ingrédient par son identifiant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ingrédient trouvé et retourné avec succès
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '404':
          description: Ingrédient non trouvé
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
              example:
                message: "Ingredient.id=1 is not found"