spring.application.name=TD5-Spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username = postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080
